# Generated by Django 4.2.21 on 2026-06-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbour',
            name='num_adults',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='neighbour',
            name='num_children',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='neighbour',
            constraint=models.CheckConstraint(check=models.Q(('num_adults__gte', 1), ('num_adults__lte', 7)), name='neighbour_adults_range'),
        ),
        migrations.AddConstraint(
            model_name='neighbour',
            constraint=models.CheckConstraint(check=models.Q(('num_children__gte', 0), ('num_children__lte', 7)), name='neighbour_children_range'),
        ),
    ]
