# Generated by Django 4.2.21 on 2026-06-12 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_add_family_size_to_neighbour'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancelog',
            name='reason',
            field=models.CharField(choices=[('topup', 'Top-up'), ('undo', 'Undo')], default='topup', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('undone', 'Undone')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='undone_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='undone_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='undone_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
