# Generated by Django 4.2.21 on 2026-06-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transaction_undo_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_item',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='unit_cost_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='track_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('unit_cost_override__isnull', True)), fields=('cart', 'item'), name='unique_cart_item_standard'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('unit_cost_override__isnull', False)), fields=('cart', 'item', 'unit_cost_override'), name='unique_cart_item_with_override'),
        ),
    ]
