# Generated by Django 4.2.21 on 2026-06-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_extras_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='max_cost',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
