# Generated by Django 4.2.21 on 2026-06-12 15:05

from decimal import Decimal

from django.db import migrations


def create_extras_item(apps, schema_editor):
    Category = apps.get_model("core", "Category")
    Item = apps.get_model("core", "Item")

    category, _ = Category.objects.get_or_create(name="Extras")
    Item.objects.get_or_create(
        name="Extras",
        category=category,
        defaults={
            "cost": Decimal("1.00"),
            "stock_count": 0,
            "low_stock_threshold": 0,
            "track_stock": False,
            "max_cost": 5,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_extras_max_cost"),
    ]

    operations = [
        migrations.RunPython(create_extras_item, migrations.RunPython.noop),
    ]
