# Generated by Django 4.2.21 on 2026-06-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ensure_extras_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancelog',
            name='reason',
            field=models.CharField(choices=[('topup', 'Top-up'), ('undo', 'Undo'), ('reset', 'Monthly Reset')], default='topup', max_length=20),
        ),
    ]
