# Generated by Django 4.2.21 on 2026-06-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_reset_reason_to_balance_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='limit_per_checkout',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(check=models.Q(('limit_per_checkout__isnull', True), ('limit_per_checkout__gte', 1), _connector='OR'), name='item_limit_per_checkout_min_one'),
        ),
    ]
