# Generated by Django 4.2.21 on 2026-06-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_item_limit_per_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbour',
            name='is_onetime',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='neighbour',
            name='card_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
